-- KPI : métrique LATE_EARLY_DEPARTURE_HOURS (retards d'arrivée / départs
-- précipités non justifiés, cumul en heures).

-- AlterTable
ALTER TABLE `KpiDefinition` MODIFY `metric` ENUM('SALES_COUNT', 'SALES_AMOUNT', 'RESILIATION_COUNT', 'COMMISSION_AMOUNT', 'ENCAISSEMENT_AMOUNT', 'CRM_ACTIVITIES_DONE', 'CRM_VISITS', 'CRM_CALLS', 'PROSPECT_CONVERSION_RATE', 'NEW_POTENTIAL_PROSPECTS', 'SOCIAL_PUBLICATIONS_COUNT', 'SOCIAL_VIEWS', 'SOCIAL_INTERACTIONS', 'SOCIAL_FOLLOWERS_GROWTH', 'ATTENDANCE_RATE', 'OVERTIME_HOURS', 'ABSENCE_DAYS', 'LATE_EARLY_DEPARTURE_HOURS', 'MANUAL_VALUE') NOT NULL DEFAULT 'MANUAL_VALUE';
