-- KPI : métrique RESILIATION_COUNT (nombre de conventions résiliées).

-- AlterTable
ALTER TABLE `KpiDefinition` MODIFY `metric` ENUM('SALES_COUNT', 'SALES_AMOUNT', 'RESILIATION_COUNT', 'COMMISSION_AMOUNT', 'ENCAISSEMENT_AMOUNT', 'CRM_ACTIVITIES_DONE', 'CRM_VISITS', 'CRM_CALLS', 'PROSPECT_CONVERSION_RATE', 'ATTENDANCE_RATE', 'OVERTIME_HOURS', 'ABSENCE_DAYS', 'MANUAL_VALUE') NOT NULL DEFAULT 'MANUAL_VALUE';
