-- AlterTable : ajout de la valeur NON_DEFINI à l'énumération PaymentMethod
ALTER TABLE `Contract` MODIFY `paymentMethod` ENUM('ESPECE', 'CHEQUE', 'TRANSFERT', 'VIREMENT', 'MOBILE_MONEY', 'NON_DEFINI') NOT NULL DEFAULT 'ESPECE';
ALTER TABLE `Payment` MODIFY `method` ENUM('ESPECE', 'CHEQUE', 'TRANSFERT', 'VIREMENT', 'MOBILE_MONEY', 'NON_DEFINI') NOT NULL;
ALTER TABLE `SaleInstallment` MODIFY `paymentMethod` ENUM('ESPECE', 'CHEQUE', 'TRANSFERT', 'VIREMENT', 'MOBILE_MONEY', 'NON_DEFINI') NULL;
ALTER TABLE `Commission` MODIFY `paymentMethod` ENUM('ESPECE', 'CHEQUE', 'TRANSFERT', 'VIREMENT', 'MOBILE_MONEY', 'NON_DEFINI') NULL;
