-- KPI : source PROSPECTS + métrique PROSPECT_CONVERSION_RATE (taux de conversion prospects → clients).

-- AlterTable
ALTER TABLE `KpiDefinition` MODIFY `source` ENUM('SALES', 'COMMISSIONS', 'ACCOUNTING', 'CRM', 'PROSPECTS', 'ATTENDANCE', 'LEAVE', 'PROJECT', 'MANUAL') NOT NULL DEFAULT 'MANUAL',
    MODIFY `metric` ENUM('SALES_COUNT', 'SALES_AMOUNT', 'COMMISSION_AMOUNT', 'ENCAISSEMENT_AMOUNT', 'CRM_ACTIVITIES_DONE', 'CRM_VISITS', 'CRM_CALLS', 'PROSPECT_CONVERSION_RATE', 'ATTENDANCE_RATE', 'OVERTIME_HOURS', 'ABSENCE_DAYS', 'MANUAL_VALUE') NOT NULL DEFAULT 'MANUAL_VALUE';
