-- KPI : source SOCIAL (réseaux sociaux / site web) + métriques
-- SOCIAL_PUBLICATIONS_COUNT, SOCIAL_VIEWS, SOCIAL_INTERACTIONS,
-- SOCIAL_FOLLOWERS_GROWTH.

-- AlterTable
ALTER TABLE `KpiDefinition` MODIFY `source` ENUM('SALES', 'COMMISSIONS', 'ACCOUNTING', 'CRM', 'PROSPECTS', 'ATTENDANCE', 'LEAVE', 'PROJECT', 'SOCIAL', 'MANUAL') NOT NULL DEFAULT 'MANUAL',
    MODIFY `metric` ENUM('SALES_COUNT', 'SALES_AMOUNT', 'RESILIATION_COUNT', 'COMMISSION_AMOUNT', 'ENCAISSEMENT_AMOUNT', 'CRM_ACTIVITIES_DONE', 'CRM_VISITS', 'CRM_CALLS', 'PROSPECT_CONVERSION_RATE', 'NEW_POTENTIAL_PROSPECTS', 'SOCIAL_PUBLICATIONS_COUNT', 'SOCIAL_VIEWS', 'SOCIAL_INTERACTIONS', 'SOCIAL_FOLLOWERS_GROWTH', 'ATTENDANCE_RATE', 'OVERTIME_HOURS', 'ABSENCE_DAYS', 'MANUAL_VALUE') NOT NULL DEFAULT 'MANUAL_VALUE';
