-- AlterTable : informations RH et état civil de l'utilisateur
ALTER TABLE `User` ADD COLUMN `fonction` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `idNumber` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `civilite` ENUM('MONSIEUR', 'MADAME', 'MADEMOISELLE') NULL;
ALTER TABLE `User` ADD COLUMN `statutConjugal` ENUM('CELIBATAIRE', 'MARIEE', 'CONCUBINAGE') NULL;
ALTER TABLE `User` ADD COLUMN `hireDate` DATETIME(3) NULL;
ALTER TABLE `User` ADD COLUMN `cnpsNumber` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `residence` VARCHAR(191) NULL;
