-- KPI : métrique RECOVERY_RATE (taux de recouvrement, global entreprise) —
-- pour l'évaluation des commerciaux et du comptable.

-- AlterTable
ALTER TABLE `KpiDefinition` MODIFY `metric` ENUM('SALES_COUNT', 'SALES_AMOUNT', 'RESILIATION_COUNT', 'COMMISSION_AMOUNT', 'ENCAISSEMENT_AMOUNT', 'RECOVERY_RATE', 'CRM_ACTIVITIES_DONE', 'CRM_VISITS', 'CRM_CALLS', 'PROSPECT_CONVERSION_RATE', 'NEW_POTENTIAL_PROSPECTS', 'SOCIAL_PUBLICATIONS_COUNT', 'SOCIAL_VIEWS', 'SOCIAL_INTERACTIONS', 'SOCIAL_FOLLOWERS_GROWTH', 'ATTENDANCE_RATE', 'OVERTIME_HOURS', 'ABSENCE_DAYS', 'LATE_EARLY_DEPARTURE_HOURS', 'IT_INNOVATIONS_IMPLEMENTED', 'MANUAL_VALUE') NOT NULL DEFAULT 'MANUAL_VALUE';
